---

- hosts: all 
  become: true 
  tasks: 
 
  - name: install httpd package 
    dnf:
      name: httpd 
      state: latest
    when: ansible_distribution == "RedHat"  
  
  - name: Update package index
    dnf:
      update_cache: yes


  - name: install flatpak package 
    dnf: 
      name: flatpak
      state: latest
