---

- hosts: all 
  become: true 
  tasks: 
 
  - name: install httpd package 
    dnf:
      name: 
        - "{{ httpd_package }}"
      state: latest 

      name:
        - "{{ flatpak_package }}"
      state: latest
